// ============================================================
//  北大347 历年真题（2012–2026），由「北大347历年真题题目（2026）.xlsx」整理。
//  已修正识别错字；subject 沿用表格里的科目标签（其他→管理）；topics 指向 exam.js 的考点 id。
//  想加新一年的题：照格式往数组里加一行即可。
// ============================================================
export const QUESTIONS = [
  {"id": "2026-1", "year": 2026, "no": "1", "score": 20, "subject": "普心", "text": "举例说明什么是学习中的正强化和负强化。", "topics": ["reinforcement"]},
  {"id": "2026-2", "year": 2026, "no": "2", "score": 20, "subject": "普心", "text": "简述工作记忆的三成分模型，并说明工作记忆和短时记忆的差别", "topics": ["working_memory"]},
  {"id": "2026-3", "year": 2026, "no": "3", "score": 20, "subject": "实验", "text": "举例说明什么是自变量混淆？如何防止出现自变量混淆？", "topics": ["iv_confound"]},
  {"id": "2026-4", "year": 2026, "no": "4", "score": 20, "subject": "统计", "text": "研究者调查某公司 50名员工的收入情况，直方图显示数据呈现严重的右偏态分布，少数高管收入极高，大部分普通员工的收入较低。报告收入的“平均数”是否合适？为了准确表述该公司员工收入的典型水平，应该采用什么统计量？请说明理由。", "topics": ["central_tendency"]},
  {"id": "2026-5", "year": 2026, "no": "5", "score": 20, "subject": "统计", "text": "单因素方差分析后要比较不同水平之间的差异，确定方差分析显著性的根源。既然这样，为什么不直接对该因素不同水平采取t检验，请说明理由。", "topics": ["anova"]},
  {"id": "2026-6", "year": 2026, "no": "6", "score": 20, "subject": "社会", "text": "短剧是出现在短视频平台的新生事物，很多短剧爆火出圈说明了观众对其接受度很高，请从社会心理学角度说明短剧被接受的原因有哪些。", "topics": ["social_influence"]},
  {"id": "2026-7", "year": 2026, "no": "7", "score": 20, "subject": "实验", "text": "简述什么会影响婴儿在视崖实验中的表现？", "topics": ["depth_cliff"]},
  {"id": "2026-8", "year": 2026, "no": "8", "score": 20, "subject": "测量", "text": "举例说明常模研究的目的是什么。", "topics": ["norms"]},
  {"id": "2026-9", "year": 2026, "no": "9", "score": 40, "subject": "综合", "text": "传统心理学中常用错误信念任务、对言语讽刺暗示的察觉等方法来测量人们心理理论的能力。目前，很多大语言模型在这些测验中取得了和人类相当的分数。这是否说明了大语言模型具备了心理理论的能力？为什么？", "topics": ["tom", "psych_ai"]},
  {"id": "2026-10", "year": 2026, "no": "10", "score": 20, "subject": "普心", "text": "压力和进食行为之间存在什么关系？请举例说明。", "topics": ["eating"]},
  {"id": "2026-11", "year": 2026, "no": "11", "score": 40, "subject": "综合", "text": "在父母养育中，每个家庭都有不同的对子女表达爱的方式，有歌中唱到“爱字有心，心有好歹”，同样表达爱的方式，什么是好的爱，什么是不好的爱，该如何测量？请首先定义“父母对子女的爱”；并结合一种心理学理论，探讨什么是“好的爱”；随后阐述，如何设计一种量表，测量家庭中父母对子女爱的类型。", "topics": ["scale_dev", "parenting"]},
  {"id": "2026-12", "year": 2026, "no": "12", "score": 40, "subject": "综合", "text": "某地区初中生休学率很高，该地教育与医疗机构建议关注初中生的心理问题。你认为，从心理学的角度，青少年休学的重点关注方面是什么？请根据你的思考，设计一种方案，改善这一情况。", "topics": ["adolescence", "depression", "anxiety"]},
  {"id": "2025-1", "year": 2025, "no": "1", "score": 20, "subject": "综合", "text": "结合实际说明什么是习得性无助", "topics": ["learned_helplessness"]},
  {"id": "2025-2", "year": 2025, "no": "2", "score": 20, "subject": "普心", "text": "短时记忆编码容量有限，人一般能随机记住多少个词汇或英文字母？如何增强短时记忆信息的编码？", "topics": ["stm_capacity"]},
  {"id": "2025-3", "year": 2025, "no": "3", "score": 20, "subject": "实验", "text": "结合实验说明混合设计的优点", "topics": ["design_types"]},
  {"id": "2025-4", "year": 2025, "no": "4", "score": 20, "subject": "实验", "text": "对产品的熟悉程度影响产品的喜爱评价，请设计一个实验验证这个观点", "topics": ["mere_exposure", "experiment_design"]},
  {"id": "2025-5", "year": 2025, "no": "5", "score": 20, "subject": "统计", "text": "“相关不等于因果”结合实例从心理学的角度分析。", "topics": ["correlation_causation"]},
  {"id": "2025-6", "year": 2025, "no": "6", "score": 20, "subject": "社会", "text": "举例说明影响社会认知发展的因素", "topics": ["social_perception", "tom"]},
  {"id": "2025-7", "year": 2025, "no": "7", "score": 20, "subject": "测量", "text": "互联网提供了越来越多的平台，一个同学在四个平台测试了智力，结果分别为120、126、132、135，由此他认为自己的智力高于一般水平。请评估互联网智力检测的可信度。", "topics": ["reliability", "validity", "norms"]},
  {"id": "2025-8", "year": 2025, "no": "8", "score": 20, "subject": "普心", "text": "有人认为人有快系统和慢系统，是否科学以及理由。", "topics": ["dual_thinking"]},
  {"id": "2025-9", "year": 2025, "no": "9", "score": 40, "subject": "普心", "text": "心理学与AI融合发展的今天，请评估人工智能模仿人类思维过程的可行性", "topics": ["psych_ai", "dual_thinking"]},
  {"id": "2025-10.1", "year": 2025, "no": "10.1", "score": 20, "subject": "社会", "text": "在日常生活中你从哪些渠道获取信息，并讨论在上述过程中存在的社会影响。", "topics": ["social_influence"]},
  {"id": "2025-10.2", "year": 2025, "no": "10.2", "score": 20, "subject": "综合", "text": "当代手机广泛使用，请结合心理学理论谈谈手机对青少年心理健康的影响。", "topics": ["adolescence"]},
  {"id": "2025-11.1", "year": 2025, "no": "11.1", "score": 40, "subject": "管理", "text": "领导者更多的是一个“成事者”而不是一个“做事者”。这句话能体现有效领导论吗？请写出支持或反对的原因，简要评论。", "topics": ["leadership"]},
  {"id": "2025-11.2", "year": 2025, "no": "11.2", "score": 40, "subject": "变态", "text": "创伤性事件可能会导致精神障碍，结合个人经历举例两个精神障碍，从不同的角度谈谈对个人心理发生发展的影响。", "topics": ["ptsd", "anxiety", "depression"]},
  {"id": "2025-12.1", "year": 2025, "no": "12.1", "score": 40, "subject": "管理", "text": "请阐述你对工作满意度的理解。假设你作为一个领导，当员工工作满意度较低时，你会采取什么样的方式？为什么", "topics": ["work_attitudes"]},
  {"id": "2025-12.2", "year": 2025, "no": "12.2", "score": 40, "subject": "测量", "text": "目前在中国大陆的综合医院或者专科医院中，心理测评的使用已经十分普遍。请结合你的当前行业中心理测评的现实情况，谈谈目前在这个领域使用心理测评的常见问题，并给出解决方案。", "topics": ["test_use"]},
  {"id": "2024-1", "year": 2024, "no": "1", "score": 20, "subject": "普心", "text": "“远看像一条狗，近看也像一条狗，原来就是一条狗”这里说明了知觉的哪些特性？", "topics": ["perception_props"]},
  {"id": "2024-2", "year": 2024, "no": "2", "score": 20, "subject": "社会", "text": "在社会交往中，我们常被告知“设身处地”、“换位思考”。请简述其中的心理学原理。", "topics": ["empathy"]},
  {"id": "2024-3", "year": 2024, "no": "3", "score": 20, "subject": "综合", "text": "有家长抱怨自己家的小朋友吃饭的时候一定要看电视。请从社会心理学的角度帮助这位家长解决孩子看电视的问题，确保小朋友身心能健康发展。", "topics": ["parenting", "reinforcement"]},
  {"id": "2024-4", "year": 2024, "no": "4", "score": 20, "subject": "综合", "text": "在某国的一个全国性调查中，91%的妻子认为自己承担了大部分的食物采购，但只有76%的丈夫同意这一点。请分析并陈述其中的心理学原理。", "topics": ["attribution"]},
  {"id": "2024-5", "year": 2024, "no": "5", "score": 20, "subject": "综合", "text": "生活在同一家庭中的兄弟姐妹可能有不同的发展结果，你怎样解释", "topics": ["heritability"]},
  {"id": "2024-6", "year": 2024, "no": "6", "score": 20, "subject": "发展", "text": "有观点认为，对学龄前儿童过早进行识字教育，会影响儿童创造力发展。请从发展心理学的角度分析该观点。", "topics": ["preschool"]},
  {"id": "2024-7", "year": 2024, "no": "7", "score": 20, "subject": "普心", "text": "珍妮·古道尔长期致力于黑猩猩野外研究，她的工作揭示了黑猩猩社群中的行为模式，纠正了许多学术界长期以来的错误认识。她曾表示“如果我不在动物的自然栖息地观察动物我将不能得到任何发现”。简述你对这句话的理解这体现了哪一种行为测量法请列出这种方法的至少两个优点和两个缺点。", "topics": ["methods"]},
  {"id": "2024-8", "year": 2024, "no": "8", "score": 20, "subject": "测量", "text": "小学二年级的小明参加了学校组织的韦氏儿童智力测验得分为145分，被标识为天才，请简述如何收集更多的材料，进一步检验该测验得分的有效性。", "topics": ["validity"]},
  {"id": "2024-9", "year": 2024, "no": "9", "score": 20, "subject": "综合", "text": "简述临床心理学中研究和临床实践的关系。", "topics": ["clinical_trial", "counseling"]},
  {"id": "2024-10", "year": 2024, "no": "10", "score": 40, "subject": "综合", "text": "在科学研究中应用人工智能是一个热门话题，你认为人工智能在心理学研究和实践中的应用场景有哪些？试举一例，分析目标、技术和可能的结果", "topics": ["psych_ai"]},
  {"id": "2024-11", "year": 2024, "no": "11", "score": 40, "subject": "综合", "text": "小赵大学毕业参加工作，经过两年多的培养，工作能力有较明显的提高，但在遇到工作问题时却常常往后退，怀疑自己干不好。如果你是小赵的直接上司，你如何根据心理学相关原理与知识来帮助小赵？", "topics": ["self_efficacy"]},
  {"id": "2024-12", "year": 2024, "no": "12", "score": 40, "subject": "综合", "text": "新闻中经常有关于未成年人校园霸凌的报道，请从心理学的角度讨论校园霸凌的成因、预防以及干预方案，并结合我国国情分析可行性。", "topics": ["adolescence", "aggression"]},
  {"id": "2023-1", "year": 2023, "no": "1", "score": 20, "subject": "普心", "text": "当今社会的生活节奏快，工作压力大，由此引发人们的情绪反应，甚至带来心理应激，人们对情绪的调节和个人的认知以及相应的应对方式有关，简述认知评价如何调节情绪。", "topics": ["emotion_appraisal"]},
  {"id": "2023-2", "year": 2023, "no": "2", "score": 20, "subject": "综合", "text": "有研究表明，相对于惩罚儿童的错误行为，及时奖赏正确行为可能更有效，结合心理学理论评述这一观点。", "topics": ["reinforcement", "parenting"]},
  {"id": "2023-3", "year": 2023, "no": "3", "score": 20, "subject": "普心", "text": "俗话说，管理深处是激励，列举说明至少三种激励或动机理论，并简述其主要的内涵。", "topics": ["motivation"]},
  {"id": "2023-4", "year": 2023, "no": "4", "score": 20, "subject": "统计", "text": "某企业想要调查员工对企业管理者的满意度，对部分员工进行了问卷访谈。这是一种典型的抽样调查方式，简述在这个调查中总体是什么样本是什么？", "topics": ["sampling"]},
  {"id": "2023-5", "year": 2023, "no": "5", "score": 20, "subject": "实验", "text": "在开始以人类为被试的研究前，参与者经历知情同意的过程，请说明知情同意的目的是什么？", "topics": ["ethics"]},
  {"id": "2023-6", "year": 2023, "no": "6", "score": 20, "subject": "综合", "text": "在骑行比赛中，有他人一起骑行比独自一人骑行速度要更快，这一现象反映出什么心理学原理，请分析和解释", "topics": ["social_facilitation"]},
  {"id": "2023-7", "year": 2023, "no": "7", "score": 20, "subject": "社会", "text": "心理学家做过这样的实验，分别让两组同学调教老鼠走迷宫，告诉a组使用特殊喂养的“聪明鼠”，b组则使用较迟钝的“愚笨鼠”，但实际实验使用的老鼠为随机分配。实验结果显示使用“聪明鼠”的a组调教过程所花费的时间明显低于“愚笨鼠”的b组。请简述实验所反映的社会心理学效应。", "topics": ["expectancy", "extraneous_control"]},
  {"id": "2023-8", "year": 2023, "no": "8", "score": 20, "subject": "综合", "text": "如果在与某个人单独会谈的过程中，你发现自己与对方的关系出现紧张，对方开始以沉默来对抗，你会做出哪些反应？简述反应所反映的心理学原理。", "topics": ["empathy", "counseling"]},
  {"id": "2023-9", "year": 2023, "no": "9", "score": 20, "subject": "变态", "text": "在生活中某人对很多事物存在担心，比如出门需要花更多的时间检查水电门窗是否关好工作中，对于数据也比其他人要多检查几遍担心犯错以后出现大问题还特别担心自己和亲人的健康判断可能是什么方面的心理问题。", "topics": ["anxiety", "ocd"]},
  {"id": "2023-10", "year": 2023, "no": "10", "score": 40, "subject": "普心", "text": "自控力是个体控制自身冲动、情感、欲望等的能力，对个人的发展和社会和谐稳定至关重要，根据心理学的知识，分析有什么因素导致自控力失效，并提出提高自控力的建议。", "topics": ["self_control"]},
  {"id": "2023-11", "year": 2023, "no": "11", "score": 40, "subject": "实验", "text": "日常人际交往过程中，善于站在对方的角度考虑问题，会促进人际沟通和理解，请设计实验验证这一观点。", "topics": ["empathy", "experiment_design"]},
  {"id": "2023-12", "year": 2023, "no": "12", "score": 40, "subject": "综合", "text": "日常生活中，具有良好生活习惯（如健康饮食、规律作息、经常锻炼等）的人不太会出现危险驾驶行为（如：超速驾驶、饮酒后开车、开车使用手机等），有研究者认为生活习惯和驾驶行为背后存在共同的影响因素，您认为共同的影响因素有哪些，请解释说明。", "topics": ["self_control", "personality"]},
  {"id": "2022-1", "year": 2022, "no": "1", "score": 20, "subject": "实验", "text": "结合实验设计，说明无意识加工的测量方法。", "topics": ["unconscious"]},
  {"id": "2022-2", "year": 2022, "no": "2", "score": 20, "subject": "普心", "text": "举例说明框架Framing效应", "topics": ["decision"]},
  {"id": "2022-3", "year": 2022, "no": "3", "score": 20, "subject": "发展", "text": "根据埃里克森的理论，描述学龄前、小学和中学阶段的心理发展特点。", "topics": ["erikson"]},
  {"id": "2022-4", "year": 2022, "no": "4", "score": 20, "subject": "测量", "text": "简述为什么测验标准化是必要的。", "topics": ["standardization"]},
  {"id": "2022-5", "year": 2022, "no": "5", "score": 20, "subject": "普心", "text": "简述自我知觉理论和认知失调理论的异同。", "topics": ["dissonance"]},
  {"id": "2022-6", "year": 2022, "no": "6", "score": 20, "subject": "管理", "text": "简述公平理论的核心内容以及人们恢复公平的方法。", "topics": ["equity_goal"]},
  {"id": "2022-7", "year": 2022, "no": "7", "score": 20, "subject": "普心", "text": "简述记忆的编码特异性。", "topics": ["encoding_specificity"]},
  {"id": "2022-8", "year": 2022, "no": "8", "score": 20, "subject": "变态", "text": "简述创伤后应激障碍的治疗方法，并比较这些方法的异同。", "topics": ["ptsd"]},
  {"id": "2022-9", "year": 2022, "no": "9", "score": 20, "subject": "变态", "text": "简述强迫症的特征。", "topics": ["ocd"]},
  {"id": "2022-10", "year": 2022, "no": "10", "score": 40, "subject": "实验", "text": "亲社会行为的产生有哪些心理学解释？请设计研究考察亲社会行为的成因。", "topics": ["prosocial", "experiment_design"]},
  {"id": "2022-11", "year": 2022, "no": "11", "score": 40, "subject": "实验", "text": "有研究考察了积极反馈和消极反馈对儿童成绩的影响，结果发现表扬成绩出众的同学会导致他们的成绩下降，而鞭策成绩下游的同学会导致他们的成绩明显提升。因此，研究者得出结论：消极反馈更能提高学生的学习表现。请评价这个实验设计，并设计研究考察积极反馈和消极反馈对学生的影响。", "topics": ["design_critique", "experiment_design"]},
  {"id": "2022-12", "year": 2022, "no": "12", "score": 40, "subject": "实验", "text": "有观点认为攻击行为是先天的，也有观点认为攻击行为是后天习得的。请辨析这两种观点，并设计实验进行验证。", "topics": ["aggression", "experiment_design"]},
  {"id": "2021-1", "year": 2021, "no": "1", "score": 20, "subject": "社会", "text": "简述社会刻板印象。", "topics": ["stereotype"]},
  {"id": "2021-2", "year": 2021, "no": "2", "score": 20, "subject": "测量", "text": "简述研究者如何确定某个心理测验的预测效度。", "topics": ["validity"]},
  {"id": "2021-3", "year": 2021, "no": "3", "score": 20, "subject": "普心", "text": "简述人格的五因素模型。", "topics": ["personality"]},
  {"id": "2021-4", "year": 2021, "no": "4", "score": 20, "subject": "普心", "text": "简述知觉的格式塔原则和基于时间、空间的知觉组织原理。", "topics": ["gestalt"]},
  {"id": "2021-5", "year": 2021, "no": "5", "score": 20, "subject": "实验", "text": "简述如何通过实验获得系列位置曲线。", "topics": ["serial_position"]},
  {"id": "2021-6", "year": 2021, "no": "6", "score": 20, "subject": "社会", "text": "简述基本归因错误及文化差异。", "topics": ["attribution"]},
  {"id": "2021-7", "year": 2021, "no": "7", "score": 20, "subject": "普心", "text": "简述乔姆斯基关于语言发展的理论以及其支持证据。", "topics": ["language"]},
  {"id": "2021-8", "year": 2021, "no": "8", "score": 20, "subject": "变态", "text": "简述精神分裂症的类型和临床主要症状。", "topics": ["schizophrenia"]},
  {"id": "2021-9", "year": 2021, "no": "9", "score": 20, "subject": "普心", "text": "简述麦克利兰三重需要理论的内容。", "topics": ["motivation"]},
  {"id": "2021-10", "year": 2021, "no": "10", "score": 40, "subject": "社会", "text": "请说明什么是从众？什么是服从？两者之间的区别是什么？并分别描述关于这两个概念的经典社会心理学实验。", "topics": ["conformity"]},
  {"id": "2021-11", "year": 2021, "no": "11", "score": 40, "subject": "实验", "text": "有理论认为，个体进食量不仅取决于个体内部饥饿信号，他人在场时，给他人留下好的印象也是我们进食的重要动机，请设计实验验证这一观点。", "topics": ["eating", "experiment_design"]},
  {"id": "2021-12", "year": 2021, "no": "12", "score": 40, "subject": "实验", "text": "研究表明，新冠疫情的爆发影响民众的心理健康水平。有研究者发现为期12周，每周一次的团体认知行为治疗可以显著降低参与者的焦虑水平。请设计一个临床实验检验这种团体认知行为疗法对于降低疫情所引发的焦虑的效果。并简要描述支持此治疗方法有效果的预期实验结果，以及不支持此治疗方法有效果的预期实验结果。", "topics": ["clinical_trial", "experiment_design", "anxiety"]},
  {"id": "2020-1", "year": 2020, "no": "1", "score": 20, "subject": "发展", "text": "简述婴儿object permanence客体永存的发展并举例说明。", "topics": ["piaget"]},
  {"id": "2020-2", "year": 2020, "no": "2", "score": 20, "subject": "普心", "text": "请解释认知过程中的序列加工和平行加工。", "topics": ["serial_parallel"]},
  {"id": "2020-3", "year": 2020, "no": "3", "score": 20, "subject": "社会", "text": "请解释社会支持的含义，以及在社会生活中的益处。", "topics": ["relationships"]},
  {"id": "2020-4", "year": 2020, "no": "4", "score": 20, "subject": "普心", "text": "看黄色轮转一段时间再看白色会看见什么？哪个理论可以来解释，请简述该理论。", "topics": ["color_vision"]},
  {"id": "2020-5", "year": 2020, "no": "5", "score": 20, "subject": "实验", "text": "双盲控制法是什么？有什么作用？", "topics": ["extraneous_control"]},
  {"id": "2020-6", "year": 2020, "no": "6", "score": 20, "subject": "统计", "text": "请解释假设检验显著性和效应量的关系。", "topics": ["hypothesis_testing"]},
  {"id": "2020-7", "year": 2020, "no": "7", "score": 20, "subject": "变态", "text": "请简述用认知疗法对抑郁症患者的认知治疗策略。", "topics": ["depression"]},
  {"id": "2020-8", "year": 2020, "no": "8", "score": 20, "subject": "测量", "text": "请说明投射测验自陈测验优缺点。", "topics": ["personality_tests"]},
  {"id": "2020-9", "year": 2020, "no": "9", "score": 20, "subject": "普心", "text": "请阐述自我效能的含义。请问自我效能感的提高途径有哪些？", "topics": ["self_efficacy"]},
  {"id": "2020-10", "year": 2020, "no": "10", "score": 40, "subject": "实验", "text": "有研究认为，人们容易将熟悉的面孔识别为积极情绪，且这一效应存在性别差异，请设计实验研究。", "topics": ["mere_exposure", "experiment_design"]},
  {"id": "2020-11", "year": 2020, "no": "11", "score": 40, "subject": "综合", "text": "智力与创造力有什么关系，用实验或企业案例来说明如何提高个体的创造力", "topics": ["intelligence"]},
  {"id": "2020-12", "year": 2020, "no": "12", "score": 40, "subject": "普心", "text": "决策判断中常使用启发式判断有哪几种？如何影响我们的判断？举例说明启发式判断中有时可能会不正确", "topics": ["decision"]},
  {"id": "2019-1", "year": 2019, "no": "1", "score": 20, "subject": "普心", "text": "快速眼动睡眠有何特点？它在睡眠周期所占的比例如何随年龄发生变化", "topics": ["sleep"]},
  {"id": "2019-2", "year": 2019, "no": "2", "score": 20, "subject": "普心", "text": "我们的视野中为什么存在盲点？如何通过简单方法测量盲点在视野中的位置？", "topics": ["blind_spot"]},
  {"id": "2019-3", "year": 2019, "no": "3", "score": 20, "subject": "普心", "text": "陈述性记忆和程序性记忆有何本质区别", "topics": ["decl_proc"]},
  {"id": "2019-4", "year": 2019, "no": "4", "score": 20, "subject": "普心", "text": "请描述A型人格的行为模式", "topics": ["type_a"]},
  {"id": "2019-5", "year": 2019, "no": "5", "score": 20, "subject": "统计", "text": "在线性回归分析中，对某一自变量显著性通常用t检验，但另一思路可以进行全模型和简化模型的比较，即F检验。请简单描述两类检验的思想以及它们是否可以互相替代使用。", "topics": ["regression_tests"]},
  {"id": "2019-6", "year": 2019, "no": "6", "score": 20, "subject": "测量", "text": "心理测验在研究和生活中应用很广，请具体说明心理测验的作用。", "topics": ["test_use"]},
  {"id": "2019-7", "year": 2019, "no": "7", "score": 20, "subject": "发展", "text": "根据皮亚杰的理论简述儿童中期个体的认知发展特点。", "topics": ["piaget"]},
  {"id": "2019-8", "year": 2019, "no": "8", "score": 20, "subject": "综合", "text": "请简述工作倦怠的内涵，并说明工作倦怠的影响后果", "topics": ["work_attitudes"]},
  {"id": "2019-9", "year": 2019, "no": "9", "score": 20, "subject": "变态", "text": "简述用来标识“变态”的标准有哪些。", "topics": ["abnormal_criteria"]},
  {"id": "2019-10", "year": 2019, "no": "10", "score": 40, "subject": "社会", "text": "从社会心理学的研究中选择两个经典研究，说明这些研究揭示了什么道理。", "topics": ["social_classics"]},
  {"id": "2019-11", "year": 2019, "no": "11", "score": 40, "subject": "实验", "text": "简述被试间设计和被试内设计的异同", "topics": ["design_types"]},
  {"id": "2019-12", "year": 2019, "no": "12", "score": 40, "subject": "实验", "text": "请设计实验考察对于外倾特点的人来说，工作压力如何影响他们的业绩", "topics": ["personality", "experiment_design"]},
  {"id": "2018-1", "year": 2018, "no": "1", "score": 20, "subject": "综合", "text": "什么是遗传力？人类行为遗传学有哪两种主要用来估计某种行为的遗传力的研究方法。", "topics": ["heritability"]},
  {"id": "2018-2", "year": 2018, "no": "2", "score": 20, "subject": "统计", "text": "独立样本t检验与相关样本t检验各有什么优势？请简述原因。", "topics": ["t_tests"]},
  {"id": "2018-3", "year": 2018, "no": "3", "score": 20, "subject": "统计", "text": "请简述假设检验中的一型错误（TypeⅠerror）和二型错误（Type Ⅱ error）分别是指什么？", "topics": ["hypothesis_testing"]},
  {"id": "2018-4", "year": 2018, "no": "4", "score": 20, "subject": "测量", "text": "如何估算测验的半分信度？使用该方法进行信度的估算有什么前提？", "topics": ["reliability"]},
  {"id": "2018-5", "year": 2018, "no": "5", "score": 20, "subject": "发展", "text": "简述陌生情境测验以及由此区分的婴儿依恋类型及其特点。", "topics": ["attachment"]},
  {"id": "2018-6", "year": 2018, "no": "6", "score": 20, "subject": "发展", "text": "举例说明发展研究中的同辈效应（cohort effect）。", "topics": ["dev_designs"]},
  {"id": "2018-7", "year": 2018, "no": "7", "score": 20, "subject": "管理", "text": "在当代经营环境下，组织中的员工有多少种失去工作的方式？请简要说明。", "topics": ["hr_practices"]},
  {"id": "2018-8", "year": 2018, "no": "8", "score": 20, "subject": "管理", "text": "简述员工援助计划(employee assistance programs, EAP)的主要内容以及其对企业/组织管理的积极意义。", "topics": ["hr_practices"]},
  {"id": "2018-9", "year": 2018, "no": "9", "score": 20, "subject": "变态", "text": "简述DSM-5身份认同障碍的诊断标准。", "topics": ["did"]},
  {"id": "2018-10", "year": 2018, "no": "10", "score": 40, "subject": "普心", "text": "简要评述说明需要层次理论的主要观点。", "topics": ["motivation"]},
  {"id": "2018-11", "year": 2018, "no": "11", "score": 40, "subject": "实验", "text": "请设计实验考察意识和无意识加工的质的差异。", "topics": ["unconscious", "experiment_design"]},
  {"id": "2018-12", "year": 2018, "no": "12", "score": 40, "subject": "社会", "text": "请论述“社会影响”的途径以及每条途径背后的心理机制。", "topics": ["social_influence", "conformity"]},
  {"id": "2017-1", "year": 2017, "no": "1", "score": 20, "subject": "普心", "text": "什么是系列位置效应？它是如何产生的？", "topics": ["serial_position"]},
  {"id": "2017-2", "year": 2017, "no": "2", "score": 20, "subject": "测量", "text": "举例说明什么是准则（效标）关联效度？举例几个准则（效标）关联效度的具体指标。", "topics": ["validity"]},
  {"id": "2017-3", "year": 2017, "no": "3", "score": 20, "subject": "发展", "text": "简述婴儿动作发展的顺序。", "topics": ["motor_dev"]},
  {"id": "2017-4", "year": 2017, "no": "4", "score": 20, "subject": "发展", "text": "儿童道德感发展分为哪几个阶段（科尔伯格理论）？每个阶段有什么特点？", "topics": ["kohlberg"]},
  {"id": "2017-5", "year": 2017, "no": "5", "score": 20, "subject": "实验", "text": "什么是自变量混淆？如何防止出现自变量混淆？", "topics": ["iv_confound"]},
  {"id": "2017-6", "year": 2017, "no": "6", "score": 20, "subject": "社会", "text": "你赞同实名上网还是匿名上网？请从社会心理学视角谈谈理由。", "topics": ["social_influence"]},
  {"id": "2017-7", "year": 2017, "no": "7", "score": 20, "subject": "统计", "text": "在一个两因素ANOVA中，A因素（2个水平）和B因素（三个水平）的交互效应是显著的，这个结果的含义是什么？", "topics": ["anova"]},
  {"id": "2017-8", "year": 2017, "no": "8", "score": 20, "subject": "普心", "text": "简述组织承诺的三个成分/维度，以及它们与工作绩效的关系", "topics": ["work_attitudes"]},
  {"id": "2017-9", "year": 2017, "no": "9", "score": 20, "subject": "变态", "text": "列举儿童抑郁的特征。", "topics": ["depression"]},
  {"id": "2017-10", "year": 2017, "no": "10", "score": 40, "subject": "社会", "text": "归因理论描述了社会知觉者如何利用信息得出因果解释。请问：（1）在凯利的协变模型中，影响社会归因的三个维度是什么？（2）在社会归因中存在哪些错误和偏差？", "topics": ["attribution"]},
  {"id": "2017-11", "year": 2017, "no": "11", "score": 40, "subject": "普心", "text": "计划行为理论是如何解释人们的戒烟行为？", "topics": ["tpb"]},
  {"id": "2017-12", "year": 2017, "no": "12", "score": 40, "subject": "管理", "text": "辨析比较绩效考核的主要方法（至少4种）。", "topics": ["hr_practices"]},
  {"id": "2016-1", "year": 2016, "no": "1", "score": 20, "subject": "普心", "text": "广告利用了哪些学习与记忆规律？", "topics": ["advertising"]},
  {"id": "2016-2", "year": 2016, "no": "2", "score": 20, "subject": "变态", "text": "反社会人格障碍的诊断标准。", "topics": ["antisocial"]},
  {"id": "2016-3", "year": 2016, "no": "3", "score": 20, "subject": "变态", "text": "请列表比较认知行为治疗与心理动力性治疗方法的异同", "topics": ["counseling"]},
  {"id": "2016-4", "year": 2016, "no": "4", "score": 20, "subject": "测量", "text": "简述MMPI-2的效度量表的原理。", "topics": ["personality_tests"]},
  {"id": "2016-5", "year": 2016, "no": "5", "score": 20, "subject": "综合", "text": "举例说明什么是刻板印象威胁。", "topics": ["stereotype"]},
  {"id": "2016-6", "year": 2016, "no": "6", "score": 20, "subject": "实验", "text": "举例说明纵向和横断研究结合起来的优点。", "topics": ["dev_designs"]},
  {"id": "2016-7", "year": 2016, "no": "7", "score": 20, "subject": "综合", "text": "请简述解释水平理论的构建逻辑。", "topics": ["construal_level"]},
  {"id": "2016-8", "year": 2016, "no": "8", "score": 20, "subject": "管理", "text": "请结合霍兰德职业兴趣理论的内容和基本原理，谈一谈该理论对个体生涯发展和企业员工管理的意义和作用。", "topics": ["hr_practices"]},
  {"id": "2016-9", "year": 2016, "no": "9", "score": 20, "subject": "统计", "text": "请举例说明在什么情况下必须使用非参数检验，而不是参数检验。", "topics": ["nonparametric"]},
  {"id": "2016-10", "year": 2016, "no": "10", "score": 40, "subject": "社会", "text": "什么是社会知觉？社会知觉中的偏差有哪些请分别解释。", "topics": ["social_perception"]},
  {"id": "2016-11", "year": 2016, "no": "11", "score": 40, "subject": "综合", "text": "根据教育部比较保守的估计，中国目前有超过2000万以上的留守儿童，留守儿童是指父母双方或一方外出打工超过1年，而自己留在农村生活的孩子们。试分析留守经历对青少年的学习成长、职业发展会存在何种影响?请设计研究来证明你对这个问题的观点。", "topics": ["adolescence", "experiment_design"]},
  {"id": "2016-12", "year": 2016, "no": "12", "score": 40, "subject": "实验", "text": "请思考如何研究“感恩”对“风险偏好”的影响？请设计一个具体的实验探讨两者之间的关系。", "topics": ["decision", "experiment_design"]},
  {"id": "2015-1", "year": 2015, "no": "1", "score": 20, "subject": "普心", "text": "简述心理学研究方法。", "topics": ["methods"]},
  {"id": "2015-2", "year": 2015, "no": "2", "score": 20, "subject": "普心", "text": "简述注意分配的双加工理论。", "topics": ["attention_dual"]},
  {"id": "2015-3", "year": 2015, "no": "3", "score": 20, "subject": "管理", "text": "管理学中人性假设有哪些？", "topics": ["human_nature"]},
  {"id": "2015-4", "year": 2015, "no": "4", "score": 20, "subject": "管理", "text": "简述洛克目标设置理论及与目标管理理论的区别。", "topics": ["equity_goal"]},
  {"id": "2015-5", "year": 2015, "no": "5", "score": 20, "subject": "管理", "text": "简述商业组织中常用的培训模式，至少列举两种。", "topics": ["hr_practices"]},
  {"id": "2015-6", "year": 2015, "no": "6", "score": 20, "subject": "发展", "text": "简述儿童心理理论及测量。", "topics": ["tom"]},
  {"id": "2015-7", "year": 2015, "no": "7", "score": 20, "subject": "变态", "text": "DSM-5中焦虑症下亚病症种类及其诊断要点。", "topics": ["anxiety"]},
  {"id": "2015-8", "year": 2015, "no": "8", "score": 20, "subject": "变态", "text": "心理咨询与心理治疗中个案评估要点以及伦理准则。", "topics": ["counseling"]},
  {"id": "2015-9", "year": 2015, "no": "9", "score": 20, "subject": "普心", "text": "简述可得性启发（availability heuristics）和代表性启发（representative heuristics）。", "topics": ["decision"]},
  {"id": "2015-10", "year": 2015, "no": "10", "score": 30, "subject": "管理", "text": "论述领导风格理论。", "topics": ["leadership"]},
  {"id": "2015-11", "year": 2015, "no": "11", "score": 30, "subject": "实验", "text": "智力IQ和情绪智力EQ哪个对预测个体的成功更有效？请设计实验证明。", "topics": ["intelligence", "experiment_design"]},
  {"id": "2015-12", "year": 2015, "no": "12", "score": 30, "subject": "实验", "text": "一位心理医生提出了一项针对抑郁的治疗方法。设计研究方案对治疗方法疗效进行科学评估，以了解该方法对抑郁症的疗效。", "topics": ["clinical_trial", "depression", "experiment_design"]},
  {"id": "2015-13", "year": 2015, "no": "13", "score": 30, "subject": "其他", "text": "阅读以下英文材料，写出研究的基本问题、研究思路、结论、以及研究意义。（原题附英文研究材料，题库未收录原文）", "topics": ["paper_reading"]},
  {"id": "2014-1", "year": 2014, "no": "1", "score": 20, "subject": "测量", "text": "请简述心理测量中信度与效度的关系。", "topics": ["validity", "reliability"]},
  {"id": "2014-2", "year": 2014, "no": "2", "score": 20, "subject": "社会", "text": "什么叫从众？其机理是什么？", "topics": ["conformity"]},
  {"id": "2014-3", "year": 2014, "no": "3", "score": 20, "subject": "普心", "text": "请举例说明费斯廷格的认知失调理论。", "topics": ["dissonance"]},
  {"id": "2014-4", "year": 2014, "no": "4", "score": 20, "subject": "管理", "text": "请简述组织管理心理学领域中有关人性假设的理论。", "topics": ["human_nature"]},
  {"id": "2014-5", "year": 2014, "no": "5", "score": 20, "subject": "实验", "text": "什么叫霍桑效应？心理学家如何解释这个效应？", "topics": ["extraneous_control"]},
  {"id": "2014-6", "year": 2014, "no": "6", "score": 40, "subject": "普心", "text": "按照班杜拉的观点，自我效能是怎样产生的？你如何看待自我效能在个人职业发展生涯中的作用", "topics": ["self_efficacy"]},
  {"id": "2014-7", "year": 2014, "no": "7", "score": 40, "subject": "管理", "text": "能力强的员工通常会表现出高的绩效，但也因此而具有更多的外部就业与发展机会，故离职倾向也较高。如何利用所学的管理心理学知识来处理这样的困境？", "topics": ["hr_practices", "work_attitudes"]},
  {"id": "2014-8", "year": 2014, "no": "8", "score": 40, "subject": "普心", "text": "精神分析理论中的代表人物有哪些（至少说出5位）？请对这些代表人物所持有的理论观点加以必要阐释", "topics": ["schools"]},
  {"id": "2014-9", "year": 2014, "no": "9", "score": 40, "subject": "实验", "text": "如果你的研究目标是考察地震灾民的心理健康因素，请说明如何使用量化和质性的方法进行研究。", "topics": ["quant_qual"]},
  {"id": "2014-10", "year": 2014, "no": "10", "score": 40, "subject": "实验", "text": "有学者认为压力本身具有积极和消极之分，但也有学者持反对意见，认为压力是积极的还是消极的完全取决于个体的认知评价。您认同哪种观点？请设计一个研究来证明自己的观点。", "topics": ["emotion_appraisal", "experiment_design"]},
  {"id": "2013-1", "year": 2013, "no": "1", "score": 20, "subject": "普心", "text": "简述乔姆斯基对人类语言获得的看法。", "topics": ["language"]},
  {"id": "2013-2", "year": 2013, "no": "2", "score": 20, "subject": "实验", "text": "请简述视崖实验，并说明其中的自变量和因变量。", "topics": ["depth_cliff"]},
  {"id": "2013-3", "year": 2013, "no": "3", "score": 20, "subject": "社会", "text": "什么是测评的晕轮效应，请举例说明。", "topics": ["social_perception"]},
  {"id": "2013-4", "year": 2013, "no": "4", "score": 20, "subject": "社会", "text": "请解释社会懈怠（Social loafing）的概念及其影响因素，并举例说明如何在工作中降低这种现象的发生。", "topics": ["social_facilitation"]},
  {"id": "2013-5", "year": 2013, "no": "5", "score": 20, "subject": "社会", "text": "简述麦独孤对社会心理学的贡献。", "topics": ["social_classics"]},
  {"id": "2013-6", "year": 2013, "no": "6", "score": 20, "subject": "普心", "text": "哪位心理学家第一个描述外向和内向的心理特征，它是在什么理论框架内提出内外向分类的。", "topics": ["personality", "schools"]},
  {"id": "2013-7", "year": 2013, "no": "7", "score": 20, "subject": "普心", "text": "简述组织承诺的概念与主要维度。", "topics": ["work_attitudes"]},
  {"id": "2013-8", "year": 2013, "no": "8", "score": 40, "subject": "社会", "text": "什么是社会知觉？社会知觉的偏差有哪些？请分别进行解释。", "topics": ["social_perception"]},
  {"id": "2013-9", "year": 2013, "no": "9", "score": 40, "subject": "发展", "text": "论述科尔伯格关于道德发展的三水平六阶段，并针对下面的偷药的例子，依据道德发展的不同阶段，选择三个阶段进行相应的解释。A的母亲得了重病，治病的药很贵，A没有凑够钱，于是A找到药的制造者希望他可以便宜卖给自己或者以后还给他,但是制造者坚决反对，A感到很绝望，于是闯进制造者的实验室给母亲偷药，他应该这样做吗？", "topics": ["kohlberg"]},
  {"id": "2013-10", "year": 2013, "no": "10", "score": 40, "subject": "实验", "text": "某研究者进行一项认知行为对焦虑心理的治疗的疗效研究，要求采用双盲程序和控制安慰剂效应，他应该如何设计实验？", "topics": ["clinical_trial", "extraneous_control", "experiment_design"]},
  {"id": "2013-11", "year": 2013, "no": "11", "score": 40, "subject": "管理", "text": "员工进入组织需要适应过程，让员工更好更快地适应这个过程，可以促进员工和企业的双赢。请依据现场干预研究的实施规则，设计一个可行的现场干预研究的实施方案。", "topics": ["hr_practices", "experiment_design"]},
  {"id": "2012-1", "year": 2012, "no": "1", "score": 20, "subject": "普心", "text": "什么是知觉的恒常性？举例说明恒常性在知觉过程中的意义。", "topics": ["perception_props"]},
  {"id": "2012-2", "year": 2012, "no": "2", "score": 20, "subject": "普心", "text": "言语发展阶段及特点。", "topics": ["language"]},
  {"id": "2012-3", "year": 2012, "no": "3", "score": 20, "subject": "社会", "text": "社会交换理论简述。", "topics": ["relationships"]},
  {"id": "2012-4", "year": 2012, "no": "4", "score": 20, "subject": "普心", "text": "说明言语先天性的证据。", "topics": ["language"]},
  {"id": "2012-5", "year": 2012, "no": "5", "score": 20, "subject": "普心", "text": "人格类型说和维度说的异同。", "topics": ["personality"]},
  {"id": "2012-6", "year": 2012, "no": "6", "score": 20, "subject": "社会", "text": "图式的含义及类别。", "topics": ["social_perception"]},
  {"id": "2012-7", "year": 2012, "no": "7", "score": 20, "subject": "普心", "text": "人格特质论的起源及新进展。", "topics": ["personality"]},
  {"id": "2012-8", "year": 2012, "no": "8", "score": 20, "subject": "社会", "text": "基本归因偏差及在生活中的意义。", "topics": ["attribution"]},
  {"id": "2012-9", "year": 2012, "no": "9", "score": 25, "subject": "普心", "text": "论述几种情绪的重要理论及其在现实生活中的意义。", "topics": ["emotion_theories"]},
  {"id": "2012-10", "year": 2012, "no": "10", "score": 25, "subject": "综合", "text": "举例说明基因和环境对人的心理功能的共同影响。", "topics": ["heritability"]},
  {"id": "2012-11", "year": 2012, "no": "11", "score": 30, "subject": "实验", "text": "设计一项研究验证时代变迁对儿童社会化的影响。", "topics": ["dev_designs", "experiment_design"]},
  {"id": "2012-12", "year": 2012, "no": "12", "score": 30, "subject": "实验", "text": "设计一个研究方案，考察员工每天的通勤状况对工作结果的影响，并说明主要的理论依据。", "topics": ["work_attitudes", "experiment_design"]},
  {"id": "2012-13", "year": 2012, "no": "13", "score": 30, "subject": "实验", "text": "题目中是一个对拖延行为进行行为干预的效果的实验设计，进行评价并重新设计。（原题给出了一个拖延行为干预的实验设计）", "topics": ["design_critique", "experiment_design"]}
];
